import {
    Button,
    // Brush,
    VerticalBox,
    HorizontalBox,
    Slider,
    GroupBox,
    StandardTableView,
    ListView,
    ScrollView,
    // Color,
} from "std-widgets.slint";
import { Palette } from "../global.slint";

export struct MessageRow {
    ts: string,
    priority: string,
    message: string,
}

// warning - identical structure exists in the Rust code
// todo check if there is an option to have them in one place.
export struct InterfaceDefinitionSlint {
    full_screen: bool,
    bg_color: color,
    text_color_zone_1: color,
    bg_color_zone_1: color,
    unit_zone_1: string,
    text_zone_1: string,
    text_color_zone_2: color,
    bg_color_zone_2: color,
    logo_image_file: string,

}


export component AppWindow inherits Window {
    in-out property <int> weight: 42;
    in property <[MessageRow]> list-of-main-program-messages: [];
    in property <InterfaceDefinitionSlint> interface_definition;
    callback request-increase-value();
    callback request-set-value(value: int);
    background: interface_definition.bg-color;
    full-screen: interface_definition.full-screen;
    width: 1024px; height: 768px;
    // width: 800px;
    // height: 600px;
    // width: 1280px; height: 1024px;
    VerticalLayout { // main
        padding: 10px;
        HorizontalLayout { // 1st row
            alignment: space-between;
            height: 25%;
            Image {
                width: 48%;
                source: @image-url("../images/logo.png");
            }
            // Zone 1
            Rectangle {
                background: interface_definition.bg-color-zone-1;
                width: 50%;
                VerticalLayout {
                    padding: 10px;

                    Text {
                        horizontal-alignment: right;
                        text: @tr("{} {}", root.weight, root.interface_definition.unit-zone-1);
                        color: interface_definition.text-color-zone-1;
                        font-size: 64px; // problem when the font-size is > 64px with QT; export SLINT_BACKEND=winit fixes it
                        font-weight: 600;
                    }

                    Text {
                        // height: parent.height * 30%; // binding loop!
                        horizontal-alignment: right;
                        text: @tr("{}", root.interface_definition.text-zone-1);
                        color: interface_definition.text-color-zone-1;
                        font-size: 40px;
                    }
                        HorizontalBox {
                        height: 5px;
                    }
                }
            }
        }

        // Zone 2
        HorizontalLayout { 
            height: 35%;
            VerticalLayout {
                Rectangle {
                    background: interface_definition.bg-color-zone-2;
                    GroupBox {
                        width: parent.width;
                        height: parent.height;
                        VerticalLayout {
                            padding-left: 10px;
                            padding-right: 10px;
                            Rectangle {
                            }
                            for row[i] in list-of-main-program-messages: //{
                                
                                Text {
                                    font-size: 35px;
                                    x: 0; // when x set, affects y too!! Bug?
                                    // y: i * 10px;
                                    text: @tr("{}", row.message);
                                    color: white;
                                    horizontal-alignment: center;   
                                }
                                
                            }
                        }
                    }
                }
            }
       // }

        HorizontalLayout { //3rd row
            height: 25%;
        }

        HorizontalLayout { //4th row
            height: 10%;
        }
    }
}
